# Generated by Django 5.2.8 on 2025-11-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studentdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_name', models.CharField(blank=True, max_length=30, null=True)),
                ('Student_rollno', models.IntegerField(blank=True, null=True)),
                ('Student_regid', models.CharField(blank=True, max_length=30, null=True)),
                ('Student_batch', models.CharField(blank=True, max_length=30, null=True)),
                ('Student_sem', models.CharField(blank=True, max_length=30, null=True)),
                ('Student_duartion', models.CharField(blank=True, max_length=30, null=True)),
                ('Student_prof', models.ImageField(blank=True, null=True, upload_to='Student Profile Image')),
            ],
        ),
    ]
