# Generated by Django 5.2.8 on 2025-11-16 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdb',
            old_name='Student_duartion',
            new_name='Student_duration',
        ),
    ]
