# Generated by Django 5.2.8 on 2025-11-17 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherApp', '0002_rename_student_duartion_studentdb_student_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjectdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject_name', models.CharField(blank=True, max_length=30, null=True)),
                ('Subject_code', models.CharField(blank=True, max_length=30, null=True)),
                ('Subject_teacher', models.CharField(blank=True, max_length=30, null=True)),
                ('Subject_sem', models.CharField(blank=True, max_length=30, null=True)),
                ('Subject_dep', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
