# Generated by Django 5.2.8 on 2025-11-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherApp', '0003_subjectdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdb',
            name='Student_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
