# Generated by Django 5.2.8 on 2025-11-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherApp', '0004_studentdb_student_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdb',
            name='Student_phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
