# Generated by Django 5.2.8 on 2025-11-19 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherApp', '0005_alter_studentdb_student_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendancedb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now_add=True)),
                ('Status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], default='Absent', max_length=10)),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeacherApp.studentdb')),
                ('Subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeacherApp.subjectdb')),
            ],
        ),
    ]
