# Generated by Django 5.2.8 on 2025-11-19 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherApp', '0006_attendancedb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internalmarkdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Internalmark', models.IntegerField()),
                ('Totalmark', models.IntegerField()),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeacherApp.studentdb')),
                ('Subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeacherApp.subjectdb')),
            ],
        ),
    ]
