# Generated by Django 5.2.8 on 2025-11-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherApp', '0007_internalmarkdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalmarkdb',
            name='Totalmark',
            field=models.IntegerField(default=50),
        ),
    ]
