# Generated by Django 5.2.8 on 2025-11-23 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherApp', '0008_alter_internalmarkdb_totalmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdb',
            name='Student_password',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='attendancedb',
            name='Date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
