# Generated by Django 5.2.8 on 2025-11-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherApp', '0010_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='read_status',
            field=models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read')], default='sent', max_length=10),
        ),
    ]
