# Generated by Django 5.2.8 on 2025-12-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherApp', '0011_chatmessage_read_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdb',
            name='Student_confirm',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
