# Generated by Django 5.2.8 on 2025-12-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherApp', '0012_studentdb_student_confirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdb',
            name='Student_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
