# Generated by Django 5.2.8 on 2025-12-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherApp', '0013_studentdb_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='hide_student_msg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='hide_teacher_msg',
            field=models.BooleanField(default=False),
        ),
    ]
