# Generated by Django 5.2.8 on 2026-01-31 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherApp', '0014_chatmessage_hide_student_msg_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancedb',
            options={'ordering': ['Date']},
        ),
        migrations.AlterModelOptions(
            name='studentdb',
            options={'ordering': ['Student_rollno']},
        ),
        migrations.AlterField(
            model_name='studentdb',
            name='Student_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='studentdb',
            name='Student_phone',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='studentdb',
            name='Student_regid',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
