# Generated by Django 5.2.8 on 2026-01-31 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherApp', '0015_alter_attendancedb_options_alter_studentdb_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectdb',
            name='Subject_code',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subjectdb',
            name='Subject_name',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
